import { createEmptyCard } from 'ts-fsrs';

export const defaultDeck = [
  {
    id: 0,
    title: 'Two Pointers: Opposite Ends',
    pattern: 'twopointer',
    difficultyRating: 'Easy',
    front: "# Two Pointers: Opposite Ends\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Two Pointers: Opposite Ends\n\ndef fn(arr):\n    left = ans = 0\n    right = len(arr) - 1\n\n    while left < right:\n        # do some logic here with left and right\n        if CONDITION:\n            left += 1\n        else:\n            right -= 1\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 1,
    title: 'Two Pointers: Two Inputs',
    pattern: 'twopointer',
    difficultyRating: 'Easy',
    front: "# Two Pointers: Two Inputs\n\ndef fn(arr1, arr2):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Two Pointers: Two Inputs\n\ndef fn(arr1, arr2):\n    i = j = ans = 0\n\n    while i < len(arr1) and j < len(arr2):\n        # do some logic here\n        if CONDITION:\n            i += 1\n        else:\n            j += 1\n\n    while i < len(arr1):\n        # do logic\n        i += 1\n\n    while j < len(arr2):\n        # do logic\n        j += 1\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 2,
    title: 'Sliding Window',
    pattern: 'slidingwindow',
    difficultyRating: 'Easy',
    front: "# Sliding Window\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Sliding Window\n\ndef fn(arr):\n    left = ans = curr = 0\n\n    for right in range(len(arr)):\n        # do logic here to add arr[right] to curr\n\n        while WINDOW_CONDITION_BROKEN:\n            # remove arr[left] from curr\n            left += 1\n\n        # update ans\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 3,
    title: 'Build a Prefix Sum',
    pattern: 'array',
    difficultyRating: 'Easy',
    front: "# Prefix Sum\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Prefix Sum\n\ndef fn(arr):\n    prefix = [arr[0]]\n    for i in range(1, len(arr)):\n        prefix.append(prefix[-1] + arr[i])\n\n    return prefix\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 4,
    title: 'Efficient String Building',
    pattern: 'array',
    difficultyRating: 'Easy',
    front: "# Efficient String Building\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Efficient String Building\n\n# arr is a list of characters\ndef fn(arr):\n    ans = []\n    for c in arr:\n        ans.append(c)\n\n    return \"\".join(ans)\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 5,
    title: 'Linked List: Fast and Slow Pointer',
    pattern: 'linkedlist',
    difficultyRating: 'Easy',
    front: "# Linked List: Fast and Slow Pointer\n\ndef fn(head):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Linked List: Fast and Slow Pointer\n\ndef fn(head):\n    slow = head\n    fast = head\n    ans = 0\n\n    while fast and fast.next:\n        # do logic\n        slow = slow.next\n        fast = fast.next.next\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 6,
    title: 'Reversing a Linked List',
    pattern: 'linkedlist',
    difficultyRating: 'Easy',
    front: "# Reversing a Linked List\n\ndef fn(head):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Reversing a Linked List\n\ndef fn(head):\n    curr = head\n    prev = None\n    while curr:\n        next_node = curr.next\n        curr.next = prev\n        prev = curr\n        curr = next_node\n\n    return prev\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 7,
    title: 'Number of Subarrays with Exact Criteria',
    pattern: 'array',
    difficultyRating: 'Medium',
    front: "# Subarrays with Exact Criteria\n\ndef fn(arr, k):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Subarrays with Exact Criteria\n\nfrom collections import defaultdict\n\ndef fn(arr, k):\n    counts = defaultdict(int)\n    counts[0] = 1\n    ans = curr = 0\n\n    for num in arr:\n        # do logic to change curr\n        ans += counts[curr - k]\n        counts[curr] += 1\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 8,
    title: 'Monotonic Increasing Stack',
    pattern: 'stack',
    difficultyRating: 'Medium',
    front: "# Monotonic Increasing Stack\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Monotonic Increasing Stack\n\ndef fn(arr):\n    stack = []\n    ans = 0\n\n    for num in arr:\n        # for monotonic decreasing, just flip the > to <\n        while stack and stack[-1] > num:\n            # do logic\n            stack.pop()\n        stack.append(num)\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 9,
    title: 'Binary Tree: DFS (Recursive)',
    pattern: 'tree',
    difficultyRating: 'Easy',
    front: "# Binary Tree: DFS (Recursive)\n\ndef dfs(root):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Tree: DFS (Recursive)\n\ndef dfs(root):\n    if not root:\n        return\n\n    ans = 0\n\n    # do logic\n    dfs(root.left)\n    dfs(root.right)\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 10,
    title: 'Binary Tree: DFS (Iterative)',
    pattern: 'tree',
    difficultyRating: 'Medium',
    front: "# Binary Tree: DFS (Iterative)\n\ndef dfs(root):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Tree: DFS (Iterative)\n\ndef dfs(root):\n    stack = [root]\n    ans = 0\n\n    while stack:\n        node = stack.pop()\n        # do logic\n        if node.left:\n            stack.append(node.left)\n        if node.right:\n            stack.append(node.right)\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 11,
    title: 'Binary Tree: BFS',
    pattern: 'tree',
    difficultyRating: 'Medium',
    front: "# Binary Tree: BFS\n\ndef fn(root):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Tree: BFS\n\nfrom collections import deque\n\ndef fn(root):\n    queue = deque([root])\n    ans = 0\n\n    while queue:\n        current_length = len(queue)\n        # do logic for current level\n\n        for _ in range(current_length):\n            node = queue.popleft()\n            # do logic\n            if node.left:\n                queue.append(node.left)\n            if node.right:\n                queue.append(node.right)\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 12,
    title: 'Graph: DFS (Recursive)',
    pattern: 'graph',
    difficultyRating: 'Medium',
    front: "# Graph: DFS (Recursive)\n\ndef fn(graph):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Graph: DFS (Recursive)\n\ndef fn(graph):\n    def dfs(node):\n        ans = 0\n        # do some logic\n        for neighbor in graph[node]:\n            if neighbor not in seen:\n                seen.add(neighbor)\n                ans += dfs(neighbor)\n\n        return ans\n\n    seen = {START_NODE}\n    return dfs(START_NODE)\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 13,
    title: 'Graph: DFS (Iterative)',
    pattern: 'graph',
    difficultyRating: 'Medium',
    front: "# Graph: DFS (Iterative)\n\ndef fn(graph):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Graph: DFS (Iterative)\n\ndef fn(graph):\n    stack = [START_NODE]\n    seen = {START_NODE}\n    ans = 0\n\n    while stack:\n        node = stack.pop()\n        # do some logic\n        for neighbor in graph[node]:\n            if neighbor not in seen:\n                seen.add(neighbor)\n                stack.append(neighbor)\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 14,
    title: 'Graph: BFS',
    pattern: 'graph',
    difficultyRating: 'Medium',
    front: "# Graph: BFS\n\ndef fn(graph):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Graph: BFS\n\nfrom collections import deque\n\ndef fn(graph):\n    queue = deque([START_NODE])\n    seen = {START_NODE}\n    ans = 0\n\n    while queue:\n        node = queue.popleft()\n        # do some logic\n        for neighbor in graph[node]:\n            if neighbor not in seen:\n                seen.add(neighbor)\n                queue.append(neighbor)\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 15,
    title: 'Find Top K Elements with Heap',
    pattern: 'heap',
    difficultyRating: 'Medium',
    front: "# Find Top K Elements with Heap\n\ndef fn(arr, k):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Find Top K Elements with Heap\n\nimport heapq\n\ndef fn(arr, k):\n    heap = []\n    for num in arr:\n        # do some logic to push onto heap according to problem's criteria\n        heapq.heappush(heap, (CRITERIA, num))\n        if len(heap) > k:\n            heapq.heappop(heap)\n\n    return [num for num in heap]\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 16,
    title: 'Binary Search',
    pattern: 'binarysearch',
    difficultyRating: 'Easy',
    front: "# Binary Search\n\ndef fn(arr, target):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Search\n\ndef fn(arr, target):\n    left = 0\n    right = len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            # do something\n            return\n        if arr[mid] > target:\n            right = mid - 1\n        else:\n            left = mid + 1\n\n    # left is the insertion point\n    return left\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 17,
    title: 'Binary Search: Left-most Insertion Point',
    pattern: 'binarysearch',
    difficultyRating: 'Medium',
    front: "# Binary Search: Left-most Insertion Point\n\ndef fn(arr, target):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Search: Left-most Insertion Point\n\ndef fn(arr, target):\n    left = 0\n    right = len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] >= target:\n            right = mid\n        else:\n            left = mid + 1\n\n    return left\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 18,
    title: 'Binary Search: Right-most Insertion Point',
    pattern: 'binarysearch',
    difficultyRating: 'Medium',
    front: "# Binary Search: Right-most Insertion Point\n\ndef fn(arr, target):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Search: Right-most Insertion Point\n\ndef fn(arr, target):\n    left = 0\n    right = len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] > target:\n            right = mid\n        else:\n            left = mid + 1\n\n    return left\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 19,
    title: 'Binary Search: Greedy (Minimum)',
    pattern: 'binarysearch',
    difficultyRating: 'Hard',
    front: "# Binary Search: Greedy (Minimum)\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Search: Greedy (Minimum)\n\ndef fn(arr):\n    def check(x):\n        # this function is implemented depending on the problem\n        return BOOLEAN\n\n    left = MINIMUM_POSSIBLE_ANSWER\n    right = MAXIMUM_POSSIBLE_ANSWER\n    while left <= right:\n        mid = (left + right) // 2\n        if check(mid):\n            right = mid - 1\n        else:\n            left = mid + 1\n\n    return left\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 20,
    title: 'Binary Search: Greedy (Maximum)',
    pattern: 'binarysearch',
    difficultyRating: 'Hard',
    front: "# Binary Search: Greedy (Maximum)\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Binary Search: Greedy (Maximum)\n\ndef fn(arr):\n    def check(x):\n        # this function is implemented depending on the problem\n        return BOOLEAN\n\n    left = MINIMUM_POSSIBLE_ANSWER\n    right = MAXIMUM_POSSIBLE_ANSWER\n    while left <= right:\n        mid = (left + right) // 2\n        if check(mid):\n            left = mid + 1\n        else:\n            right = mid - 1\n\n    return right\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 21,
    title: 'Backtracking',
    pattern: 'backtracking',
    difficultyRating: 'Medium',
    front: "# Backtracking\n\ndef backtrack(curr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Backtracking\n\ndef backtrack(curr, OTHER_ARGUMENTS...):\n    if (BASE_CASE):\n        # modify the answer\n        return\n\n    ans = 0\n    for (ITERATE_OVER_INPUT):\n        # modify the current state\n        ans += backtrack(curr, OTHER_ARGUMENTS...)\n        # undo the modification of the current state\n\n    return ans\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 22,
    title: 'Dynamic Programming: Top-Down Memoization',
    pattern: '1Ddynamicprogramming',
    difficultyRating: 'Medium',
    front: "# Dynamic Programming: Top-Down\n\ndef fn(arr):\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Dynamic Programming: Top-Down\n\ndef fn(arr):\n    def dp(STATE):\n        if BASE_CASE:\n            return 0\n\n        if STATE in memo:\n            return memo[STATE]\n\n        ans = RECURRENCE_RELATION(STATE)\n        memo[STATE] = ans\n        return ans\n\n    memo = {}\n    return dp(STATE_FOR_WHOLE_INPUT)\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 23,
    title: 'Build a Trie',
    pattern: 'trie',
    difficultyRating: 'Medium',
    front: "# Trie\n\nclass TrieNode:\n    pass\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Trie\n\n# note: using a class is only necessary if you want to store data at each node.\n# otherwise, you can implement a trie using only hash maps.\nclass TrieNode:\n    def __init__(self):\n        # you can store data at nodes if you wish\n        self.data = None\n        self.children = {}\n\ndef fn(words):\n    root = TrieNode()\n    for word in words:\n        curr = root\n        for c in word:\n            if c not in curr.children:\n                curr.children[c] = TrieNode()\n            curr = curr.children[c]\n        # at this point, you have a full word at curr\n        # you can perform more logic here to give curr an attribute if you want\n\n    return root\n",
    stage: 'new',
    ...createEmptyCard(),
  },
  {
    id: 24,
    title: "Dijkstra's Algorithm",
    pattern: 'advancedgraph',
    difficultyRating: 'Hard',
    front: "# Dijkstra's Algorithm\n\n\n\n# Cmd+Enter to submit. Cmd+; to reveal.\n",
    back: "# Dijkstra's Algorithm\n\nfrom math import inf\nfrom heapq import *\n\ndistances = [inf] * n\ndistances[source] = 0\nheap = [(0, source)]\n\nwhile heap:\n    curr_dist, node = heappop(heap)\n    if curr_dist > distances[node]:\n        continue\n\n    for nei, weight in graph[node]:\n        dist = curr_dist + weight\n        if dist < distances[nei]:\n            distances[nei] = dist\n            heappush(heap, (dist, nei))\n",
    stage: 'new',
    ...createEmptyCard(),
  },
];
